TEAM_CATALOG: dict[tuple[str, str], tuple[str, str, str]] = {
    ("nba", "1"): ("basketball", "Atlanta Hawks", "ATL"),
    ("nba", "2"): ("basketball", "Boston Celtics", "BOS"),
    ("nba", "3"): ("basketball", "New Orleans Pelicans", "NO"),
    ("nba", "4"): ("basketball", "Chicago Bulls", "CHI"),
    ("nba", "5"): ("basketball", "Cleveland Cavaliers", "CLE"),
    ("nba", "6"): ("basketball", "Dallas Mavericks", "DAL"),
    ("nba", "7"): ("basketball", "Denver Nuggets", "DEN"),
    ("nba", "8"): ("basketball", "Detroit Pistons", "DET"),
    ("nba", "9"): ("basketball", "Golden State Warriors", "GS"),
    ("nba", "10"): ("basketball", "Houston Rockets", "HOU"),
    ("nba", "11"): ("basketball", "Indiana Pacers", "IND"),
    ("nba", "12"): ("basketball", "LA Clippers", "LAC"),
    ("nba", "13"): ("basketball", "Los Angeles Lakers", "LAL"),
    ("nba", "14"): ("basketball", "Miami Heat", "MIA"),
    ("nba", "15"): ("basketball", "Milwaukee Bucks", "MIL"),
    ("nba", "16"): ("basketball", "Minnesota Timberwolves", "MIN"),
    ("nba", "17"): ("basketball", "Brooklyn Nets", "BKN"),
    ("nba", "18"): ("basketball", "New York Knicks", "NY"),
    ("nba", "19"): ("basketball", "Orlando Magic", "ORL"),
    ("nba", "20"): ("basketball", "Philadelphia 76ers", "PHI"),
    ("nba", "21"): ("basketball", "Phoenix Suns", "PHX"),
    ("nba", "22"): ("basketball", "Portland Trail Blazers", "POR"),
    ("nba", "23"): ("basketball", "Sacramento Kings", "SAC"),
    ("nba", "24"): ("basketball", "San Antonio Spurs", "SA"),
    ("nba", "25"): ("basketball", "Oklahoma City Thunder", "OKC"),
    ("nba", "26"): ("basketball", "Utah Jazz", "UTAH"),
    ("nba", "27"): ("basketball", "Washington Wizards", "WSH"),
    ("nba", "28"): ("basketball", "Toronto Raptors", "TOR"),
    ("nba", "29"): ("basketball", "Memphis Grizzlies", "MEM"),
    ("nba", "30"): ("basketball", "Charlotte Hornets", "CHA"),
    ("wnba", "20"): ("basketball", "Atlanta Dream", "ATL"),
    ("wnba", "19"): ("basketball", "Chicago Sky", "CHI"),
    ("wnba", "18"): ("basketball", "Connecticut Sun", "CON"),
    ("wnba", "3"): ("basketball", "Dallas Wings", "DAL"),
    ("wnba", "129689"): ("basketball", "Golden State Valkyries", "GS"),
    ("wnba", "5"): ("basketball", "Indiana Fever", "IND"),
    ("wnba", "17"): ("basketball", "Las Vegas Aces", "LV"),
    ("wnba", "6"): ("basketball", "Los Angeles Sparks", "LA"),
    ("wnba", "8"): ("basketball", "Minnesota Lynx", "MIN"),
    ("wnba", "9"): ("basketball", "New York Liberty", "NY"),
    ("wnba", "11"): ("basketball", "Phoenix Mercury", "PHX"),
    ("wnba", "132052"): ("basketball", "Portland Fire", "POR"),
    ("wnba", "14"): ("basketball", "Seattle Storm", "SEA"),
    ("wnba", "131935"): ("basketball", "Toronto Tempo", "TOR"),
    ("wnba", "16"): ("basketball", "Washington Mystics", "WSH"),
    ("nfl", "22"): ("football", "Arizona Cardinals", "ARI"),
    ("nfl", "1"): ("football", "Atlanta Falcons", "ATL"),
    ("nfl", "33"): ("football", "Baltimore Ravens", "BAL"),
    ("nfl", "2"): ("football", "Buffalo Bills", "BUF"),
    ("nfl", "29"): ("football", "Carolina Panthers", "CAR"),
    ("nfl", "3"): ("football", "Chicago Bears", "CHI"),
    ("nfl", "4"): ("football", "Cincinnati Bengals", "CIN"),
    ("nfl", "5"): ("football", "Cleveland Browns", "CLE"),
    ("nfl", "6"): ("football", "Dallas Cowboys", "DAL"),
    ("nfl", "7"): ("football", "Denver Broncos", "DEN"),
    ("nfl", "8"): ("football", "Detroit Lions", "DET"),
    ("nfl", "9"): ("football", "Green Bay Packers", "GB"),
    ("nfl", "34"): ("football", "Houston Texans", "HOU"),
    ("nfl", "11"): ("football", "Indianapolis Colts", "IND"),
    ("nfl", "30"): ("football", "Jacksonville Jaguars", "JAX"),
    ("nfl", "12"): ("football", "Kansas City Chiefs", "KC"),
    ("nfl", "13"): ("football", "Las Vegas Raiders", "LV"),
    ("nfl", "24"): ("football", "Los Angeles Chargers", "LAC"),
    ("nfl", "14"): ("football", "Los Angeles Rams", "LAR"),
    ("nfl", "15"): ("football", "Miami Dolphins", "MIA"),
    ("nfl", "16"): ("football", "Minnesota Vikings", "MIN"),
    ("nfl", "17"): ("football", "New England Patriots", "NE"),
    ("nfl", "18"): ("football", "New Orleans Saints", "NO"),
    ("nfl", "19"): ("football", "New York Giants", "NYG"),
    ("nfl", "20"): ("football", "New York Jets", "NYJ"),
    ("nfl", "21"): ("football", "Philadelphia Eagles", "PHI"),
    ("nfl", "23"): ("football", "Pittsburgh Steelers", "PIT"),
    ("nfl", "25"): ("football", "San Francisco 49ers", "SF"),
    ("nfl", "26"): ("football", "Seattle Seahawks", "SEA"),
    ("nfl", "27"): ("football", "Tampa Bay Buccaneers", "TB"),
    ("nfl", "10"): ("football", "Tennessee Titans", "TEN"),
    ("nfl", "28"): ("football", "Washington Commanders", "WSH"),
    ("mlb", "1"): ("baseball", "Baltimore Orioles", "BAL"),
    ("mlb", "2"): ("baseball", "Boston Red Sox", "BOS"),
    ("mlb", "3"): ("baseball", "Los Angeles Angels", "LAA"),
    ("mlb", "4"): ("baseball", "Chicago White Sox", "CHW"),
    ("mlb", "5"): ("baseball", "Cleveland Guardians", "CLE"),
    ("mlb", "6"): ("baseball", "Detroit Tigers", "DET"),
    ("mlb", "7"): ("baseball", "Kansas City Royals", "KC"),
    ("mlb", "8"): ("baseball", "Milwaukee Brewers", "MIL"),
    ("mlb", "9"): ("baseball", "Minnesota Twins", "MIN"),
    ("mlb", "10"): ("baseball", "New York Yankees", "NYY"),
    ("mlb", "11"): ("baseball", "Athletics", "ATH"),
    ("mlb", "12"): ("baseball", "Seattle Mariners", "SEA"),
    ("mlb", "13"): ("baseball", "Texas Rangers", "TEX"),
    ("mlb", "14"): ("baseball", "Toronto Blue Jays", "TOR"),
    ("mlb", "15"): ("baseball", "Atlanta Braves", "ATL"),
    ("mlb", "16"): ("baseball", "Chicago Cubs", "CHC"),
    ("mlb", "17"): ("baseball", "Cincinnati Reds", "CIN"),
    ("mlb", "18"): ("baseball", "Houston Astros", "HOU"),
    ("mlb", "19"): ("baseball", "Los Angeles Dodgers", "LAD"),
    ("mlb", "20"): ("baseball", "Washington Nationals", "WSH"),
    ("mlb", "21"): ("baseball", "New York Mets", "NYM"),
    ("mlb", "22"): ("baseball", "Philadelphia Phillies", "PHI"),
    ("mlb", "23"): ("baseball", "Pittsburgh Pirates", "PIT"),
    ("mlb", "24"): ("baseball", "St. Louis Cardinals", "STL"),
    ("mlb", "25"): ("baseball", "San Diego Padres", "SD"),
    ("mlb", "26"): ("baseball", "San Francisco Giants", "SF"),
    ("mlb", "27"): ("baseball", "Colorado Rockies", "COL"),
    ("mlb", "28"): ("baseball", "Miami Marlins", "MIA"),
    ("mlb", "29"): ("baseball", "Arizona Diamondbacks", "ARI"),
    ("mlb", "30"): ("baseball", "Tampa Bay Rays", "TB"),
    ("soccer", "18418"): ("soccer", "Atlanta United FC", "ATL"),
    ("soccer", "20906"): ("soccer", "Austin FC", "ATX"),
    ("soccer", "9720"): ("soccer", "CF Montréal", "MTL"),
    ("soccer", "21300"): ("soccer", "Charlotte FC", "CLT"),
    ("soccer", "182"): ("soccer", "Chicago Fire FC", "CHI"),
    ("soccer", "184"): ("soccer", "Colorado Rapids", "COL"),
    ("soccer", "183"): ("soccer", "Columbus Crew", "CLB"),
    ("soccer", "193"): ("soccer", "D.C. United", "DC"),
    ("soccer", "18267"): ("soccer", "FC Cincinnati", "CIN"),
    ("soccer", "185"): ("soccer", "FC Dallas", "DAL"),
    ("soccer", "6077"): ("soccer", "Houston Dynamo FC", "HOU"),
    ("soccer", "20232"): ("soccer", "Inter Miami CF", "MIA"),
    ("soccer", "187"): ("soccer", "LA Galaxy", "LA"),
    ("soccer", "18966"): ("soccer", "LAFC", "LAFC"),
    ("soccer", "17362"): ("soccer", "Minnesota United FC", "MIN"),
    ("soccer", "18986"): ("soccer", "Nashville SC", "NSH"),
    ("soccer", "189"): ("soccer", "New England Revolution", "NE"),
    ("soccer", "17606"): ("soccer", "New York City FC", "NYC"),
    ("soccer", "12011"): ("soccer", "Orlando City SC", "ORL"),
    ("soccer", "10739"): ("soccer", "Philadelphia Union", "PHI"),
    ("soccer", "9723"): ("soccer", "Portland Timbers", "POR"),
    ("soccer", "4771"): ("soccer", "Real Salt Lake", "RSL"),
    ("soccer", "190"): ("soccer", "Red Bull New York", "RBNY"),
    ("soccer", "22529"): ("soccer", "San Diego FC", "SD"),
    ("soccer", "191"): ("soccer", "San Jose Earthquakes", "SJ"),
    ("soccer", "9726"): ("soccer", "Seattle Sounders FC", "SEA"),
    ("soccer", "186"): ("soccer", "Sporting Kansas City", "SKC"),
    ("soccer", "21812"): ("soccer", "St. Louis CITY SC", "STL"),
    ("soccer", "7318"): ("soccer", "Toronto FC", "TOR"),
    ("soccer", "9727"): ("soccer", "Vancouver Whitecaps", "VAN"),
    ("soccer", "96"): ("soccer", "Alavés", "ALA"),
    ("soccer", "93"): ("soccer", "Athletic Club", "ATH"),
    ("soccer", "1068"): ("soccer", "Atlético Madrid", "ATM"),
    ("soccer", "83"): ("soccer", "Barcelona", "BAR"),
    ("soccer", "85"): ("soccer", "Celta Vigo", "CEL"),
    ("soccer", "90"): ("soccer", "Deportivo", "DEP"),
    ("soccer", "3751"): ("soccer", "Elche", "ELC"),
    ("soccer", "88"): ("soccer", "Espanyol", "ESP"),
    ("soccer", "2922"): ("soccer", "Getafe", "GET"),
    ("soccer", "1538"): ("soccer", "Levante", "LEV"),
    ("soccer", "99"): ("soccer", "Málaga", "MCF"),
    ("soccer", "97"): ("soccer", "Osasuna", "OSA"),
    ("soccer", "87"): ("soccer", "Racing Santander", "RAC"),
    ("soccer", "101"): ("soccer", "Rayo Vallecano", "RAY"),
    ("soccer", "244"): ("soccer", "Real Betis", "BET"),
    ("soccer", "86"): ("soccer", "Real Madrid", "RMA"),
    ("soccer", "89"): ("soccer", "Real Sociedad", "RSO"),
    ("soccer", "243"): ("soccer", "Sevilla", "SEV"),
    ("soccer", "94"): ("soccer", "Valencia", "VAL"),
    ("soccer", "102"): ("soccer", "Villarreal", "VIL"),
    ("soccer", "349"): ("soccer", "AFC Bournemouth", "BOU"),
    ("soccer", "359"): ("soccer", "Arsenal", "ARS"),
    ("soccer", "362"): ("soccer", "Aston Villa", "AVL"),
    ("soccer", "337"): ("soccer", "Brentford", "BRE"),
    ("soccer", "331"): ("soccer", "Brighton & Hove Albion", "BHA"),
    ("soccer", "363"): ("soccer", "Chelsea", "CHE"),
    ("soccer", "388"): ("soccer", "Coventry City", "COV"),
    ("soccer", "384"): ("soccer", "Crystal Palace", "CRY"),
    ("soccer", "368"): ("soccer", "Everton", "EVE"),
    ("soccer", "370"): ("soccer", "Fulham", "FUL"),
    ("soccer", "306"): ("soccer", "Hull City", "HUL"),
    ("soccer", "373"): ("soccer", "Ipswich Town", "IPS"),
    ("soccer", "357"): ("soccer", "Leeds United", "LEE"),
    ("soccer", "364"): ("soccer", "Liverpool", "LIV"),
    ("soccer", "382"): ("soccer", "Manchester City", "MNC"),
    ("soccer", "360"): ("soccer", "Manchester United", "MAN"),
    ("soccer", "361"): ("soccer", "Newcastle United", "NEW"),
    ("soccer", "393"): ("soccer", "Nottingham Forest", "NFO"),
    ("soccer", "366"): ("soccer", "Sunderland", "SUN"),
    ("soccer", "367"): ("soccer", "Tottenham Hotspur", "TOT"),
    ("soccer", "624"): ("soccer", "Algeria", "ALG"),
    ("soccer", "202"): ("soccer", "Argentina", "ARG"),
    ("soccer", "628"): ("soccer", "Australia", "AUS"),
    ("soccer", "474"): ("soccer", "Austria", "AUT"),
    ("soccer", "459"): ("soccer", "Belgium", "BEL"),
    ("soccer", "452"): ("soccer", "Bosnia-Herzegovina", "BIH"),
    ("soccer", "205"): ("soccer", "Brazil", "BRA"),
    ("soccer", "206"): ("soccer", "Canada", "CAN"),
    ("soccer", "2597"): ("soccer", "Cape Verde", "CPV"),
    ("soccer", "208"): ("soccer", "Colombia", "COL"),
    ("soccer", "2850"): ("soccer", "Congo DR", "COD"),
    ("soccer", "477"): ("soccer", "Croatia", "CRO"),
    ("soccer", "11678"): ("soccer", "Curacao", "CUW"),
    ("soccer", "450"): ("soccer", "Czechia", "CZE"),
    ("soccer", "209"): ("soccer", "Ecuador", "ECU"),
    ("soccer", "2620"): ("soccer", "Egypt", "EGY"),
    ("soccer", "448"): ("soccer", "England", "ENG"),
    ("soccer", "478"): ("soccer", "France", "FRA"),
    ("soccer", "481"): ("soccer", "Germany", "GER"),
    ("soccer", "4469"): ("soccer", "Ghana", "GHA"),
    ("soccer", "2654"): ("soccer", "Haiti", "HAI"),
    ("soccer", "469"): ("soccer", "Iran", "IRN"),
    ("soccer", "4375"): ("soccer", "Iraq", "IRQ"),
    ("soccer", "4789"): ("soccer", "Ivory Coast", "CIV"),
    ("soccer", "627"): ("soccer", "Japan", "JPN"),
    ("soccer", "2917"): ("soccer", "Jordan", "JOR"),
    ("soccer", "203"): ("soccer", "Mexico", "MEX"),
    ("soccer", "2869"): ("soccer", "Morocco", "MAR"),
    ("soccer", "449"): ("soccer", "Netherlands", "NED"),
    ("soccer", "2666"): ("soccer", "New Zealand", "NZL"),
    ("soccer", "464"): ("soccer", "Norway", "NOR"),
    ("soccer", "2659"): ("soccer", "Panama", "PAN"),
    ("soccer", "210"): ("soccer", "Paraguay", "PAR"),
    ("soccer", "482"): ("soccer", "Portugal", "POR"),
    ("soccer", "4398"): ("soccer", "Qatar", "QAT"),
    ("soccer", "655"): ("soccer", "Saudi Arabia", "KSA"),
    ("soccer", "580"): ("soccer", "Scotland", "SCO"),
    ("soccer", "654"): ("soccer", "Senegal", "SEN"),
    ("soccer", "467"): ("soccer", "South Africa", "RSA"),
    ("soccer", "451"): ("soccer", "South Korea", "KOR"),
    ("soccer", "164"): ("soccer", "Spain", "ESP"),
    ("soccer", "466"): ("soccer", "Sweden", "SWE"),
    ("soccer", "475"): ("soccer", "Switzerland", "SUI"),
    ("soccer", "659"): ("soccer", "Tunisia", "TUN"),
    ("soccer", "465"): ("soccer", "Turkiye", "TUR"),
    ("soccer", "660"): ("soccer", "United States", "USA"),
    ("soccer", "212"): ("soccer", "Uruguay", "URU"),
    ("soccer", "2570"): ("soccer", "Uzbekistan", "UZB"),
}

FBS_TEAMS_BY_CONFERENCE: dict[str, tuple[tuple[str, str, str], ...]] = {
    "American": (
        ("5", "UAB Blazers", "UAB"),
        ("58", "South Florida Bulls", "USF"),
        ("151", "East Carolina Pirates", "ECU"),
        ("202", "Tulsa Golden Hurricane", "TLSA"),
        ("218", "Temple Owls", "TEM"),
        ("235", "Memphis Tigers", "MEM"),
        ("242", "Rice Owls", "RICE"),
        ("249", "North Texas Mean Green", "UNT"),
        ("349", "Army Black Knights", "ARMY"),
        ("2226", "Florida Atlantic Owls", "FAU"),
        ("2426", "Navy Midshipmen", "NAVY"),
        ("2429", "Charlotte 49ers", "CLT"),
        ("2636", "UTSA Roadrunners", "UTSA"),
        ("2655", "Tulane Green Wave", "TULN"),
    ),
    "ACC": (
        ("24", "Stanford Cardinal", "STAN"),
        ("25", "California Golden Bears", "CAL"),
        ("52", "Florida State Seminoles", "FSU"),
        ("59", "Georgia Tech Yellow Jackets", "GT"),
        ("97", "Louisville Cardinals", "LOU"),
        ("103", "Boston College Eagles", "BC"),
        ("150", "Duke Blue Devils", "DUKE"),
        ("152", "NC State Wolfpack", "NCSU"),
        ("153", "North Carolina Tar Heels", "UNC"),
        ("154", "Wake Forest Demon Deacons", "WAKE"),
        ("183", "Syracuse Orange", "SYR"),
        ("221", "Pittsburgh Panthers", "PITT"),
        ("228", "Clemson Tigers", "CLEM"),
        ("258", "Virginia Cavaliers", "UVA"),
        ("259", "Virginia Tech Hokies", "VT"),
        ("2390", "Miami Hurricanes", "MIA"),
        ("2567", "SMU Mustangs", "SMU"),
    ),
    "Big 12": (
        ("9", "Arizona State Sun Devils", "ASU"),
        ("12", "Arizona Wildcats", "ARIZ"),
        ("38", "Colorado Buffaloes", "COLO"),
        ("66", "Iowa State Cyclones", "ISU"),
        ("197", "Oklahoma State Cowboys", "OKST"),
        ("239", "Baylor Bears", "BAY"),
        ("248", "Houston Cougars", "HOU"),
        ("252", "BYU Cougars", "BYU"),
        ("254", "Utah Utes", "UTAH"),
        ("277", "West Virginia Mountaineers", "WVU"),
        ("2116", "UCF Knights", "UCF"),
        ("2132", "Cincinnati Bearcats", "CIN"),
        ("2305", "Kansas Jayhawks", "KU"),
        ("2306", "Kansas State Wildcats", "KSU"),
        ("2628", "TCU Horned Frogs", "TCU"),
        ("2641", "Texas Tech Red Raiders", "TTU"),
    ),
    "Big Ten": (
        ("26", "UCLA Bruins", "UCLA"),
        ("30", "USC Trojans", "USC"),
        ("77", "Northwestern Wildcats", "NU"),
        ("84", "Indiana Hoosiers", "IU"),
        ("120", "Maryland Terrapins", "MD"),
        ("127", "Michigan State Spartans", "MSU"),
        ("130", "Michigan Wolverines", "MICH"),
        ("135", "Minnesota Golden Gophers", "MINN"),
        ("158", "Nebraska Cornhuskers", "NEB"),
        ("164", "Rutgers Scarlet Knights", "RUTG"),
        ("194", "Ohio State Buckeyes", "OSU"),
        ("213", "Penn State Nittany Lions", "PSU"),
        ("264", "Washington Huskies", "WASH"),
        ("275", "Wisconsin Badgers", "WIS"),
        ("356", "Illinois Fighting Illini", "ILL"),
        ("2294", "Iowa Hawkeyes", "IOWA"),
        ("2483", "Oregon Ducks", "ORE"),
        ("2509", "Purdue Boilermakers", "PUR"),
    ),
    "Conference USA": (
        ("48", "Delaware Blue Hens", "DEL"),
        ("55", "Jacksonville State Gamecocks", "JVST"),
        ("98", "Western Kentucky Hilltoppers", "WKU"),
        ("166", "New Mexico State Aggies", "NMSU"),
        ("338", "Kennesaw State Owls", "KENN"),
        ("2229", "Florida International Panthers", "FIU"),
        ("2335", "Liberty Flames", "LIB"),
        ("2393", "Middle Tennessee Blue Raiders", "MTSU"),
        ("2534", "Sam Houston Bearkats", "SHSU"),
        ("2623", "Missouri State Bears", "MOST"),
    ),
    "Independent": (
        ("41", "UConn Huskies", "CONN"),
        ("87", "Notre Dame Fighting Irish", "ND"),
    ),
    "Mid-American": (
        ("16", "Sacramento State Hornets", "SAC"),
        ("113", "Massachusetts Minutemen", "MASS"),
        ("189", "Bowling Green Falcons", "BGSU"),
        ("193", "Miami (OH) RedHawks", "M-OH"),
        ("195", "Ohio Bobcats", "OHIO"),
        ("2006", "Akron Zips", "AKR"),
        ("2050", "Ball State Cardinals", "BALL"),
        ("2084", "Buffalo Bulls", "BUFF"),
        ("2117", "Central Michigan Chippewas", "CMU"),
        ("2199", "Eastern Michigan Eagles", "EMU"),
        ("2309", "Kent State Golden Flashes", "KENT"),
        ("2649", "Toledo Rockets", "TOL"),
        ("2711", "Western Michigan Broncos", "WMU"),
    ),
    "Mountain West": (
        ("23", "San José State Spartans", "SJSU"),
        ("62", "Hawai'i Rainbow Warriors", "HAW"),
        ("167", "New Mexico Lobos", "UNM"),
        ("2005", "Air Force Falcons", "AFA"),
        ("2439", "UNLV Rebels", "UNLV"),
        ("2440", "Nevada Wolf Pack", "NEV"),
        ("2449", "North Dakota State Bison", "NDSU"),
        ("2459", "Northern Illinois Huskies", "NIU"),
        ("2638", "UTEP Miners", "UTEP"),
        ("2751", "Wyoming Cowboys", "WYO"),
    ),
    "Pac-12": (
        ("21", "San Diego State Aztecs", "SDSU"),
        ("36", "Colorado State Rams", "CSU"),
        ("68", "Boise State Broncos", "BOIS"),
        ("204", "Oregon State Beavers", "ORST"),
        ("265", "Washington State Cougars", "WSU"),
        ("278", "Fresno State Bulldogs", "FRES"),
        ("326", "Texas State Bobcats", "TXST"),
        ("328", "Utah State Aggies", "USU"),
    ),
    "SEC": (
        ("2", "Auburn Tigers", "AUB"),
        ("8", "Arkansas Razorbacks", "ARK"),
        ("57", "Florida Gators", "FLA"),
        ("61", "Georgia Bulldogs", "UGA"),
        ("96", "Kentucky Wildcats", "UK"),
        ("99", "LSU Tigers", "LSU"),
        ("142", "Missouri Tigers", "MIZ"),
        ("145", "Ole Miss Rebels", "MISS"),
        ("201", "Oklahoma Sooners", "OU"),
        ("238", "Vanderbilt Commodores", "VAN"),
        ("245", "Texas A&M Aggies", "TA&M"),
        ("251", "Texas Longhorns", "TEX"),
        ("333", "Alabama Crimson Tide", "ALA"),
        ("344", "Mississippi State Bulldogs", "MSST"),
        ("2579", "South Carolina Gamecocks", "SC"),
        ("2633", "Tennessee Volunteers", "TENN"),
    ),
    "Sun Belt": (
        ("6", "South Alabama Jaguars", "USA"),
        ("256", "James Madison Dukes", "JMU"),
        ("276", "Marshall Thundering Herd", "MRSH"),
        ("290", "Georgia Southern Eagles", "GASO"),
        ("295", "Old Dominion Monarchs", "ODU"),
        ("309", "Louisiana Ragin' Cajuns", "UL"),
        ("324", "Coastal Carolina Chanticleers", "CCU"),
        ("2026", "App State Mountaineers", "APP"),
        ("2032", "Arkansas State Red Wolves", "ARST"),
        ("2247", "Georgia State Panthers", "GAST"),
        ("2348", "Louisiana Tech Bulldogs", "LT"),
        ("2433", "UL Monroe Warhawks", "ULM"),
        ("2572", "Southern Miss Golden Eagles", "USM"),
        ("2653", "Troy Trojans", "TROY"),
    ),
}
FBS_TEAMS = tuple(
    team
    for conference_teams in FBS_TEAMS_BY_CONFERENCE.values()
    for team in conference_teams
)
TEAM_CATALOG.update(
    {
        ("cfb", external_team_id): ("football", name, abbreviation)
        for external_team_id, name, abbreviation in FBS_TEAMS
    }
)
FBS_TEAM_CONFERENCES = {
    external_team_id: conference
    for conference, teams in FBS_TEAMS_BY_CONFERENCE.items()
    for external_team_id, _, _ in teams
}

COMPETITION_TEAM_IDS: dict[str, tuple[str, ...]] = {
    "NBA": (
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
    ),
    "WNBA": (
        "20",
        "19",
        "18",
        "3",
        "129689",
        "5",
        "17",
        "6",
        "8",
        "9",
        "11",
        "132052",
        "14",
        "131935",
        "16",
    ),
    "NFL": (
        "22",
        "1",
        "33",
        "2",
        "29",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "34",
        "11",
        "30",
        "12",
        "13",
        "24",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "23",
        "25",
        "26",
        "27",
        "10",
        "28",
    ),
    "FBS": tuple(external_team_id for external_team_id, _, _ in FBS_TEAMS),
    "MLB": (
        "1",
        "2",
        "3",
        "4",
        "5",
        "6",
        "7",
        "8",
        "9",
        "10",
        "11",
        "12",
        "13",
        "14",
        "15",
        "16",
        "17",
        "18",
        "19",
        "20",
        "21",
        "22",
        "23",
        "24",
        "25",
        "26",
        "27",
        "28",
        "29",
        "30",
    ),
    "MLS": (
        "18418",
        "20906",
        "9720",
        "21300",
        "182",
        "184",
        "183",
        "193",
        "18267",
        "185",
        "6077",
        "20232",
        "187",
        "18966",
        "17362",
        "18986",
        "189",
        "17606",
        "12011",
        "10739",
        "9723",
        "4771",
        "190",
        "22529",
        "191",
        "9726",
        "186",
        "21812",
        "7318",
        "9727",
    ),
    "LA_LIGA": (
        "96",
        "93",
        "1068",
        "83",
        "85",
        "90",
        "3751",
        "88",
        "2922",
        "1538",
        "99",
        "97",
        "87",
        "101",
        "244",
        "86",
        "89",
        "243",
        "94",
        "102",
    ),
    "PREMIER_LEAGUE": (
        "349",
        "359",
        "362",
        "337",
        "331",
        "363",
        "388",
        "384",
        "368",
        "370",
        "306",
        "373",
        "357",
        "364",
        "382",
        "360",
        "361",
        "393",
        "366",
        "367",
    ),
    "WORLD_CUP": (
        "624",
        "202",
        "628",
        "474",
        "459",
        "452",
        "205",
        "206",
        "2597",
        "208",
        "2850",
        "477",
        "11678",
        "450",
        "209",
        "2620",
        "448",
        "478",
        "481",
        "4469",
        "2654",
        "469",
        "4375",
        "4789",
        "627",
        "2917",
        "203",
        "2869",
        "449",
        "2666",
        "464",
        "2659",
        "210",
        "482",
        "4398",
        "655",
        "580",
        "654",
        "467",
        "451",
        "164",
        "466",
        "475",
        "659",
        "465",
        "660",
        "212",
        "2570",
    ),
}
